<?xml version="1.0"?>
<package format="3">

  <name>eliasROS2turtlesim</name>

  <version>0.0.1</version>

  <description>
    Simple WASD controller for ROS2 TurtleSim
    using Protocol Buffers.
  </description>

  <maintainer email="your@email.com">
    Your Name
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>